# Generated by Django 4.2.2 on 2023-07-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ayat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urdu", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Surah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arabic", models.TextField(blank=True, null=True)),
                ("urdu", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arabic", models.TextField(blank=True, null=True)),
                ("urdu", models.TextField(blank=True, null=True)),
                (
                    "ayat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Surah.ayat"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ayat",
            name="surah",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Surah.surah"
            ),
        ),
    ]
