# Generated by Django 4.2.2 on 2023-07-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Surah", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ayat",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surah",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
